export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      No: "01",
      carNo: 6465,
      DriverName: "Alex Noman",
      status: "Completed",
      earning: "35.44",
    },
    {
      id: 2,
      No: "02",
      carNo: 5665,
      DriverName: "Razib Rahman",
      status: "Pending",
      earning: "0.00",
    },
    {
      id: 3,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
    {
      id: 4,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
    {
      id: 5,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
    {
      id: 6,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
    {
      id: 7,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
    {
      id: 8,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
    {
      id: 9,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
    {
      id: 10,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
    {
      id: 11,
      No: "03",
      carNo: 1755,
      DriverName: "Luke Norton",
      status: "In route",
      earning: "23.50",
    },
  ]);
}
